# Generated by Django 5.0 on 2023-12-08 00:03

import django.db.models.deletion
from django.db import migrations, models
from dashboard.models import BedOccupancy

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_patient_general_patient_referenceperson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('occupied', models.BooleanField(default=False)),
                ('occupied_since', models.DateTimeField(blank=True, null=True)),
                ('admission_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient_base')),
            ],
        ),
    ]