# Generated by Django 5.0 on 2023-12-15 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_auto_20231208_0722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient_base",
            name="admission_number",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="patient_general",
            name="admission_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.patient_base"
            ),
        ),
        migrations.AlterField(
            model_name="patient_referenceperson",
            name="admission_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.patient_base"
            ),
        ),
    ]
